/blue/guo/yangh/Toy_PEDS/sh
c0304a-s10.ufhpc
Tue Aug 20 00:54:34 EDT 2024
device:cuda
Generating data:   0%|          | 0/10000 [00:00<?, ?it/s]Generating data:  94%|█████████▍| 9380/10000 [00:00<00:00, 77016.50it/s]Generating data: 100%|██████████| 10000/10000 [00:00<00:00, 79586.50it/s]
Training and validation data loaded successfully on cuda.
Testing w=0.0
Traceback (most recent call last):
  File "/blue/guo/yangh/Toy_PEDS/search_weight.py", line 62, in <module>
    train_losses, val_losses=dm.fit(params=params,learning_rate=0.1,save_path=weight_path)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/blue/guo/yangh/Toy_PEDS/DiffusionModel.py", line 90, in fit
    pred = self(x_batch,params)
           ^^^^^^^^^^^^^^^^^^^^
  File "/blue/guo/yangh/.conda/envs/PEDS/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/blue/guo/yangh/.conda/envs/PEDS/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/blue/guo/yangh/Toy_PEDS/DiffusionModel.py", line 59, in forward
    final_D = w * fine_D + (1 - w) * D_tensor
              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
